THISDIR="artifactory"
install:
	@echo "install complete in ${THISDIR}"

package:
	@echo "package complete in ${THISDIR}"

publish:
	@echo "publish complete in ${THISDIR}"

clean:
	@echo "clean complete in ${THISDIR}"
