clean:

install:
	cd ./tools;make install
	@echo "*** INSTALL COMPLETE in devtools ***"

package:
	cd ./tools;make package
	@echo "*** PACKAGE COMPLETE in devtools ***"

publish:
	cd ./tools;make publish
	@echo "*** RELEASE COMPLETE in devtools ***"
