install:
	cp setup-linux-jenkins.sh setup-win-jenkins.bat winjenk.scr /usr/local/accord/bin/
	@echo "*** INSTALL COMPLETE in jenkins ***"

package:
	@echo "*** PACKAGE COMPLETE in jenkins ***"

publish:
	./publish-scripts.sh
	@echo "*** PUBLISH COMPLETE in jenkins ***"
