#!/bin/bash
#
#  The Windows Instance: Microsoft Windows Server 2012 Base - ami-6f2cf804
#  be sure to open ports 80, 443

#  Disable firewall
#  go to Administrative Tools on the startup window
#  open “Windows Firewall with Advanced Security”

#  Download chrome rather than using IE -- IE did not let me download anything
#  everything was a security violation.

set JENKINS=jenkins-1.624.zip
set JAVAVER=jdk-8u51-windows-x64.exe
set JHOME="C:\Program Files\Java\jdk1.8.0_51"

#
# install java
#

#
# get the java sdk and install it
#
cd ~Administrator/
curl -O unzip.exe --user accord:AP4GxDHU2f6EriLqry781wG6fy http://ec2-52-6-164-191.compute-1.amazonaws.com/artifactory/ext-tools/java/unzip.exe
curl -O $JAVAVER --user accord:AP4GxDHU2f6EriLqry781wG6fy http://ec2-52-6-164-191.compute-1.amazonaws.com/artifactory/ext-tools/java/$JAVAVER
chmod +x $JAVAVER
echo "Starting jdk installation...
./$JAVAVER /s
echo "installation complete"

#
# ensure that the windows system environment variables for JAVA
# are set up properly and that the default PATH will find the
# java programs
#
echo "Setting System environment variables JAVA_HOME and PATH..."
echo "Updating global path to include $JAVAHOME/bin"
echo "use the setx command which needs to run from a command prompt"
cmd /C setx /M JAVA_HOME "$JHOME"
cmd /C setx /M Path "$JHOME\bin"

#
# get the latest jenkins
#
curl -O $JENKINS.zip --user accord:AP4GxDHU2f6EriLqry781wG6fy http://ec2-52-6-164-191.compute-1.amazonaws.com/artifactory/ext-tools/utils/$JENKINS
chmod +x unzip.exe
./unzip.exe $JENKINS
