#!/bin/bash
#
#  The Windows Instance: Microsoft Windows Server 2012 Base - ami-6f2cf804
#  be sure to open ports 80, 443

#  Disable firewall
#  go to Administrative Tools on the startup window
#  open “Windows Firewall with Advanced Security”

#  Download chrome rather than using IE -- IE did not let me download anything
#  everything was a security violation.

#  Use chrome to download Cygwin from https://cygwin.com/install.html

#  Setup cygwin install and in addition to the base system get these packages:
#      wget, curl, unzip, git
#
#  TODO: Cygwin's setup.exe program can run in silent mode... we need to
#        research this and figure out how to give it all the parameters it needs

# At this point, it is assumed that we have the cygwin tools in place.
# Open a bash shell and invoke this script.

#
# install java
#

#
# get the java sdk and install it
#
# TODO: move the windows java distribution into Artifactory
#       or better yet, see if there is someplace on the internet that lets
#       a script download the jdk
wget http://stevemansour.com/accord/jdk-8u51-windows-x64.exe
chmod +x jdk-8u51-windows-x64.exe
echo "Starting jdk installation...
./jdk-8u51-windows-x64.exe /s
echo "installation complete

#
# ensure that the windows system environment variables for JAVA
# are set up properly and that the default PATH will find the
# java programs
#
echo "Setting System environment variables JAVA_HOME and PATH..."
echo "Updating global path to include $JAVAHOME/bin"
echo "use the setx command which needs to run from a command prompt"
cmd /C setx /M JAVA_HOME "c:\Program Files\Java\jdk1.8.0_51"
cmd /C setx /M Path "%PATH%;%JAVA_HOME%/bin"

#
# get the latest jenkins
#
wget -O jenkins.zip http://mirrors.jenkins-ci.org/windows/latest
unzip jenkins.zip

