install:
	cd ./artifactory;make install
	cd ./jenkins;make install
	@echo "*** INSTALL COMPLETE in ci ***"

package:
	cd ./artifactory;make package
	cd ./jenkins;make package
	@echo "*** INSTALL COMPLETE in ci ***"

publish:
	cd ./artifactory;make publish
	cd ./jenkins;make publish
	@echo "*** INSTALL COMPLETE in ci ***"
