install:
	cp build/libs/publicdns.jar /usr/local/accord/jars/publicdns.jar
	cp build/classes/main/PublicDNS.class /usr/local/accord/jars/
	cp publicdns /usr/local/accord/bin/
	cp lnxinstall.sh /usr/local/accord/bin
	@echo "*** INSTALL COMPLETE in publicdns ***"

package:
	@echo "*** PACKAGE COMPLETE in publicdns ***"

publish:
	@echo "*** PUBLISH COMPLETE in publicdns ***"